# This has secrets! Do not use this config for anything but local testing
# with minikube.

# the binder apiToken bit requires jupyterhub helm-chart v0.5.x

custom:
  cors:
    allowOrigin: "*"

hub:
  cookieSecret: "36091e950f98f033aeae2520e2fe4c8599bc391598f910e510ad670765fbc1ff"
  db:
    type: "sqlite-memory"
  services:
    binder:
      apiToken: "aec7d32df938c0f55e54f09244a350cb29ea612907ed4f07be13d9553d18a8e4"
  allowNamedServers: false
  extraConfig:
    10-binder-customisations: |
      # debug!
      c.JupyterHub.log_level = 10

proxy:
  # Another secret!
  secretToken: "443fa28905c209eaf5803f911de7748f443c78062767d9d28d514dc4fbefd843"
  service:
    type: NodePort
    nodePorts:
      http: 30123
