version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout

      - run:
          name: Install NPM
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
            sudo apt-get install -y nodejs

      # Install documentation requirements in the same way that ReadTheDocs
      # does to check our dependencies are all specified
      - run:
          name: Install doc dependencies
          command: |
            sudo pip install -r doc/doc-requirements.txt

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd doc
            make html

      - store_artifacts:
          path: doc/_build/html/
          destination: html

workflows:
  version: 2
  default:
    jobs:
      - build_docs
